import json
import pytest
from datetime import datetime, timedelta
from unittest.mock import patch, mock_open

from fpl_tuner import (
    FPLWeights,
    TuningConfig,
    ConfigManager,
    FPLTuningOrchestrator,
    TuningEngine
)
from diagnostic_logger import setup_diagnostic_logging

# --- Fixtures ---

@pytest.fixture
def workspace_dir(tmp_path):
    """Provides an isolated temporary directory to act as the workspace."""
    # Initialize the multi-file log structures in the temp workspace
    setup_diagnostic_logging(tmp_path)
    return tmp_path

@pytest.fixture
def config_manager(workspace_dir):
    return ConfigManager(workspace_dir)

@pytest.fixture
def orchestrator(workspace_dir):
    return FPLTuningOrchestrator(workspace_path=str(workspace_dir))

# --- 1. Parameter-Aging Trigger Logic ---

class TestParameterAging:
    
    @patch('fpl_tuner.datetime')
    def test_aging_trigger_thresholds(self, mock_datetime, orchestrator):
        """Verifies the optimization fires exactly when the elapsed time threshold is crossed."""
        # Anchor time
        base_time = datetime(2026, 5, 1, 12, 0)
        
        # Mock a configuration saved exactly 7 days before the base time
        stale_date = base_time - timedelta(days=7)
        config = TuningConfig(
            weights=FPLWeights(),
            last_updated=stale_date.isoformat()
        )
        
        # We must route fromisoformat back to the real datetime class to parse our string
        mock_datetime.fromisoformat = datetime.fromisoformat
        
        # Test Case A: Time is 6.99 days elapsed -> Should NOT trigger
        mock_datetime.now.return_value = base_time - timedelta(minutes=5)
        assert orchestrator.is_stale(config) is False

        # Test Case B: Time is exactly 7 days + 1 second elapsed -> SHOULD trigger
        mock_datetime.now.return_value = base_time + timedelta(seconds=1)
        assert orchestrator.is_stale(config) is True


# --- 2. Notebook-to-Solver Boundary Assertions ---

class TestBoundaryAssertions:
    
    def test_strict_schema_enforcement(self):
        """Ensures that invalid configurations generated by the notebook are rejected before hitting the solver."""
        with pytest.raises(ValueError, match="fixture_weight must be between 0 and 5"):
            bad_weights = FPLWeights(fixture_weight=99.9)
            bad_weights.validate()

    def test_notebook_write_solver_read(self, config_manager):
        """Simulates the boundary where a Notebook UI saves a config and the Solver reads it asynchronously."""
        # 1. Simulate Notebook override
        notebook_weights = FPLWeights(fixture_weight=2.75, form_decay=0.45)
        config = TuningConfig(weights=notebook_weights)
        config_manager.save_config(config)
        
        # 2. Simulate Solver Engine startup reading the canonical state
        solver_config = config_manager.load_active_config()
        
        assert solver_config.weights.fixture_weight == 2.75
        assert solver_config.weights.form_decay == 0.45
        assert solver_config.weights.positional_variance == 1.0 # Default untouched


# --- 3. Edge Case Injection ---

class TestEdgeCases:
    
    def test_corrupted_config_factory_reset(self, config_manager, capsys):
        """Ensures an interrupted write or corrupted JSON triggers a safe baseline fallback, preventing solver crashes."""
        # Inject corrupted JSON
        with open(config_manager.config_path, "w") as f:
            f.write("{invalid_json: true, trailing_comma: }")
            
        # The manager should catch JSONDecodeError and return baseline weights
        fallback_config = config_manager.load_active_config()
        
        assert fallback_config.weights == FPLWeights()  # Verified as baseline
        captured = capsys.readouterr()
        assert "CRITICAL: Config corrupted" in captured.out

    @patch('fpl_tuner.open')
    def test_locked_configuration_file_handling(self, mock_open_func, config_manager):
        """Simulates an OS-level lock (e.g., notebook is currently writing while solver tries to read)."""
        mock_open_func.side_effect = PermissionError("Resource temporarily unavailable")
        
        # Test how the system responds to a PermissionError when loading
        # (It should currently raise, but this test exposes that we might want to catch it and fallback)
        with pytest.raises(PermissionError):
             config_manager.load_active_config()
             
    @patch.object(TuningEngine, 'run_parallel_optimization')
    def test_interrupted_tuning_task(self, mock_optimize, orchestrator, config_manager):
        """Simulates an optimization task that fails mid-execution (e.g., memory exhaustion)."""
        mock_optimize.side_effect = MemoryError("Worker process ran out of memory")
        
        # Force a run to guarantee the tuning engine is invoked
        with pytest.raises(MemoryError):
            orchestrator.run(force=True)
            
        # Verify that the active config was NOT updated/corrupted by the failed run
        # Since it crashed before saving, load_active_config should return the baseline.
        config = config_manager.load_active_config()
        assert config.weights == FPLWeights()
